import { db } from "./database"
import type { Food } from "@/types/database"

const sampleFoods: Omit<Food, "id" | "createdAt" | "updatedAt">[] = [
  // Proteins
  {
    name: "Chicken Breast (cooked)",
    source: "custom",
    servingSize: 100,
    servingUnit: "g",
    servingSizeGrams: 100,
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    category: "protein",
    tags: ["meat", "lean"],
    isFavorite: true,
  },
  {
    name: "Eggs (large)",
    source: "custom",
    servingSize: 1,
    servingUnit: "piece",
    servingSizeGrams: 50,
    calories: 72,
    protein: 6.3,
    carbs: 0.4,
    fat: 5,
    fiber: 0,
    category: "protein",
    tags: ["breakfast"],
    isFavorite: true,
  },
  {
    name: "Greek Yogurt (plain, nonfat)",
    source: "custom",
    servingSize: 170,
    servingUnit: "g",
    servingSizeGrams: 170,
    calories: 100,
    protein: 17,
    carbs: 6,
    fat: 0.7,
    fiber: 0,
    category: "dairy",
    tags: ["breakfast", "snack"],
    isFavorite: true,
  },
  {
    name: "Salmon (cooked)",
    source: "custom",
    servingSize: 100,
    servingUnit: "g",
    servingSizeGrams: 100,
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
    category: "protein",
    tags: ["fish", "omega-3"],
    isFavorite: false,
  },
  {
    name: "Cottage Cheese (low fat)",
    source: "custom",
    servingSize: 113,
    servingUnit: "g",
    servingSizeGrams: 113,
    calories: 81,
    protein: 14,
    carbs: 3,
    fat: 1,
    fiber: 0,
    category: "dairy",
    tags: ["snack"],
    isFavorite: false,
  },

  // Grains & Carbs
  {
    name: "Brown Rice (cooked)",
    source: "custom",
    servingSize: 1,
    servingUnit: "cup",
    servingSizeGrams: 195,
    calories: 216,
    protein: 5,
    carbs: 45,
    fat: 1.8,
    fiber: 3.5,
    category: "grains",
    tags: ["whole grain"],
    isFavorite: false,
  },
  {
    name: "Oatmeal (cooked)",
    source: "custom",
    servingSize: 1,
    servingUnit: "cup",
    servingSizeGrams: 234,
    calories: 158,
    protein: 6,
    carbs: 27,
    fat: 3.2,
    fiber: 4,
    category: "grains",
    tags: ["breakfast", "whole grain"],
    isFavorite: true,
  },
  {
    name: "Whole Wheat Bread",
    source: "custom",
    servingSize: 1,
    servingUnit: "slice",
    servingSizeGrams: 43,
    calories: 81,
    protein: 4,
    carbs: 14,
    fat: 1,
    fiber: 2,
    category: "grains",
    tags: ["whole grain"],
    isFavorite: false,
  },
  {
    name: "Sweet Potato (baked)",
    source: "custom",
    servingSize: 1,
    servingUnit: "piece",
    servingSizeGrams: 150,
    calories: 135,
    protein: 3,
    carbs: 31,
    fat: 0.1,
    fiber: 4.5,
    category: "vegetables",
    tags: ["root vegetable"],
    isFavorite: false,
  },

  // Vegetables (high fiber)
  {
    name: "Broccoli (cooked)",
    source: "custom",
    servingSize: 1,
    servingUnit: "cup",
    servingSizeGrams: 156,
    calories: 55,
    protein: 3.7,
    carbs: 11,
    fat: 0.6,
    fiber: 5.1,
    category: "vegetables",
    tags: ["green vegetable"],
    isFavorite: true,
  },
  {
    name: "Spinach (raw)",
    source: "custom",
    servingSize: 2,
    servingUnit: "cup",
    servingSizeGrams: 60,
    calories: 14,
    protein: 1.7,
    carbs: 2.2,
    fat: 0.2,
    fiber: 1.3,
    category: "vegetables",
    tags: ["leafy green"],
    isFavorite: false,
  },
  {
    name: "Black Beans (cooked)",
    source: "custom",
    servingSize: 0.5,
    servingUnit: "cup",
    servingSizeGrams: 86,
    calories: 114,
    protein: 7.6,
    carbs: 20,
    fat: 0.5,
    fiber: 7.5,
    category: "protein",
    tags: ["legume", "high fiber"],
    isFavorite: true,
  },
  {
    name: "Lentils (cooked)",
    source: "custom",
    servingSize: 0.5,
    servingUnit: "cup",
    servingSizeGrams: 99,
    calories: 115,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 8,
    category: "protein",
    tags: ["legume", "high fiber"],
    isFavorite: false,
  },
  {
    name: "Avocado",
    source: "custom",
    servingSize: 0.5,
    servingUnit: "piece",
    servingSizeGrams: 100,
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
    fiber: 7,
    category: "fats",
    tags: ["healthy fat", "high fiber"],
    isFavorite: false,
  },

  // Fruits
  {
    name: "Banana",
    source: "custom",
    servingSize: 1,
    servingUnit: "piece",
    servingSizeGrams: 118,
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
    fiber: 3.1,
    category: "fruits",
    tags: ["snack"],
    isFavorite: true,
  },
  {
    name: "Apple",
    source: "custom",
    servingSize: 1,
    servingUnit: "piece",
    servingSizeGrams: 182,
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
    fiber: 4.4,
    category: "fruits",
    tags: ["snack"],
    isFavorite: false,
  },
  {
    name: "Blueberries",
    source: "custom",
    servingSize: 1,
    servingUnit: "cup",
    servingSizeGrams: 148,
    calories: 84,
    protein: 1.1,
    carbs: 21,
    fat: 0.5,
    fiber: 3.6,
    category: "fruits",
    tags: ["berries"],
    isFavorite: false,
  },
  {
    name: "Raspberries",
    source: "custom",
    servingSize: 1,
    servingUnit: "cup",
    servingSizeGrams: 123,
    calories: 64,
    protein: 1.5,
    carbs: 15,
    fat: 0.8,
    fiber: 8,
    category: "fruits",
    tags: ["berries", "high fiber"],
    isFavorite: false,
  },

  // Fats
  {
    name: "Olive Oil",
    source: "custom",
    servingSize: 1,
    servingUnit: "tbsp",
    servingSizeGrams: 14,
    calories: 119,
    protein: 0,
    carbs: 0,
    fat: 14,
    fiber: 0,
    category: "fats",
    tags: ["healthy fat", "cooking oil"],
    isFavorite: false,
  },
  {
    name: "Almonds",
    source: "custom",
    servingSize: 1,
    servingUnit: "oz",
    servingSizeGrams: 28,
    calories: 164,
    protein: 6,
    carbs: 6,
    fat: 14,
    fiber: 3.5,
    category: "fats",
    tags: ["nuts", "snack"],
    isFavorite: false,
  },
  {
    name: "Chia Seeds",
    source: "custom",
    servingSize: 1,
    servingUnit: "tbsp",
    servingSizeGrams: 12,
    calories: 58,
    protein: 2,
    carbs: 5,
    fat: 3.7,
    fiber: 4.1,
    category: "fats",
    tags: ["seeds", "high fiber", "omega-3"],
    isFavorite: true,
  },
]

export async function seedDatabase(): Promise<void> {
  const existingCount = await db.foods.count()

  if (existingCount === 0) {
    const now = new Date()
    const foodsWithIds: Food[] = sampleFoods.map((food) => ({
      ...food,
      id: crypto.randomUUID(),
      createdAt: now,
      updatedAt: now,
    }))

    await db.foods.bulkAdd(foodsWithIds)
    console.log(`Seeded database with ${foodsWithIds.length} foods`)
  }
}
